add_test([=[JuntaListasTest.ValidMerge]=]  /home/aluno/.a/alg-fabbri-IPRJ-UERJ/alg/merge/tests/run-merge-tests [==[--gtest_filter=JuntaListasTest.ValidMerge]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[JuntaListasTest.ValidMerge]=]  PROPERTIES WORKING_DIRECTORY /home/aluno/.a/alg-fabbri-IPRJ-UERJ/alg/merge/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[JuntaListasTest.UnsortedInput]=]  /home/aluno/.a/alg-fabbri-IPRJ-UERJ/alg/merge/tests/run-merge-tests [==[--gtest_filter=JuntaListasTest.UnsortedInput]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[JuntaListasTest.UnsortedInput]=]  PROPERTIES WORKING_DIRECTORY /home/aluno/.a/alg-fabbri-IPRJ-UERJ/alg/merge/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  run-merge-tests_TESTS JuntaListasTest.ValidMerge JuntaListasTest.UnsortedInput)
